### ISSUE TITLE
Set website language from domain

### ISSUE THREAD

**Issue by gergo85** [rainlab/translate-plugin#102]
There are two domain names and one webpage. I tried the following code, but it didn't work:
```
function onStart()
{
    $domain = Request::root();

    if ($domain == 'http://exampledomain.ru') {
        $locale = 'ru';
    }

    else if ($domain == 'http://exampledomain.en') {
        $locale = 'en';
    }

    App::setLocale($locale);
}
```

**Comment by AlbertCalvet** [comment]
Ok, I was interested in this as well, so here's what I did. You might consider creating a function in a separate file or whataver since I guess an update will override the file but, to give an idea, in the routes file from the translate-plugin I did this change:

    //$locale = Request::segment(1);
	
	switch (substr(Request::root(), strrpos(Request::root(), ".")+1))
	{
		case 'cat':
		$locale = 'ca';
		break;
		
		case 'com':
		$locale = 'en';
		break;
		
		case 'es':
		$locale = 'es';
		break;
	}

Which I got a comment on this article:
http://ryantablada.com/post/multi-tld-routing-in-laravel

Then on the nav bar I set the links each to a different url based on TLD and that's it, a quick fix.

**Comment by gergo85** [comment]
Thank you very much for your help! It was life-saving.

**Comment by sqwk** [comment]
Would this still append `/en` or `/ru` to both tlds? Is there a way to prevent this and tie the language directly to the tld?
