### ISSUE TITLE
Is there support for markdown editor?

### ISSUE THREAD

**Issue by mabasic** [rainlab/translate-plugin#106]

**Comment by daftspunk** [comment]
Yes, `MLMarkdownEditor` now exists

**Comment by u-michiel** [comment]
I'm trying to use it for content blocks in the Rainlab.Pages plugin.

I replaced the editor in the Rainlab.Pages plugin with the MLMarkdownEditor, it reads the language files correctly, even when I switch languages. (Switching between content.md and content.nl.md works) Saving the default file works as well (content.md), but saving the translated file (content.nl.md) doesn't work.

It says: "... has been successfully saved.", but the file wasn't written to.
Same goes if there is no translated file yet and you switch to a language and try to save the file.

This is working for richeditor (gets replaced by mlricheditor), that's why I'm thinking it's a bug in the translate plugin?
