### ISSUE TITLE
Translate File

### ISSUE THREAD

**Issue by jbartoszek** [rainlab/translate-plugin#113]
Currently this plugin is not support types of field like: AttachOne, AttachMany.
It would be nice to have this feature.

I would see it that language to selecting  in modal after upload files and enter in title and description per language(for SEO)

**Comment by andreconghau** [comment]
Hi there,
i have met similar problem.
Can anybody help?

Thank!

**Comment by CptMeatball** [comment]
A workaround might be to use a file upload through the mediamanager and implement this inside a repeater. It's not the cleanest way, but it might do the job.

**Comment by andreconghau** [comment]
Hi @CptMeatball ,

That's is good idea right now. But i want somthing like Drupal File Entity Translation. Thanks for your suggestion

Cheer

**Comment by andreconghau** [comment]
Hi @Glitchbone ,

That's is my expectation. But if we are able to translate files, it will be better than.

For example: in my case, i just want to show image_en.png for english version and image_fr.png for french version. It meant that we have 2 image uploaded.

Currently, I have to create 2 fields and show/hide by js. This is not good.

Thanks

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

**Comment by Alex360hd** [comment]
Would be greate to integrate the Glitchbone plugin to the core translate plugin

**Comment by LukeTowers** [comment]
@Alex360hd feel free to do that :)

**Comment by Alex360hd** [comment]
I can try even if I can't promise anything as I don't know well october cms yet neigher laravel.

**Comment by LukeTowers** [comment]
No worries, give it a try, you'll probably learn a lot about both :)

**Comment by LukeTowers** [comment]
This has been implemented in #470

**Comment by patrick-durrer** [comment]
For the implementation of multilingual websites we often cannot use the actual fileuploader because the files only can be added  generally without any relation to a language. Especially if there is text on a picture or a document with text in it. We then have to switch to the mediafinder or create a separate attachment for each language: `image_de`,` image_en`, `image_fr` etc. We would like to solve this via the fileuploader that we like very much (apart from this).

Visualisation example: 

![Example for multilingual File-Upload](https://user-images.githubusercontent.com/15232963/103216989-c00bb400-4917-11eb-8f69-b8087ced9c9b.png)

How realistic do you see this feature being implemented? If there is a general need for this, we would like to post a bounty (200$) for this feature.

**Comment by mjauvin** [comment]
@patrick-durrer please open another issue for this as this issue has been resolved.
