### ISSUE TITLE
404 Page Translation

### ISSUE THREAD

**Issue by portal7** [rainlab/translate-plugin#124]
All works good, but no translation content on 404 page.. there appear all the codetag like {{ 'site.partforexample'|_}}

**Comment by blacked7** [comment]
Hi @portal7 I have the same issue and it seems to be that the Translate plugin boot method has a listener to the event "cms.page.beforeDisplay" and tracking where does October fires this event and I found that is in the file modules/cms/classes/Controller.php on line 183, the problem is that this event is fired up before the controller assigns the error page so for the Translate plugin the page is null and it can be translated :-(

Maybe we can ask for a modification in this file to fire the event after the error page is assigned.

P.S. Sorry about my english :S

**Comment by portal7** [comment]
Ok, voy a probar eso a ver en que resulta. Muchas Gracias desde Argentina ;)

**Comment by blacked7** [comment]
Jajaja Saludos desde México!

**Comment by daftspunk** [comment]
Replicated.

1. Open the 404.htm page for any theme
1. Add a `{{ 'hello'|_ }}` translation
1. Navigate to System > Translate messages in backend
1. String does not appear and cannot be translated

Notes

Check the CmsController because 404 redirection occurs so early and doesn't fire the standard events (used by Translate).

**Comment by blacked7** [comment]
Hi there @daftspunk maybe this can help, I just changed the position of the beforeDisplay event in the file modules/cms/classes/Controller.php on line 182
[Controller.zip](https://github.com/rainlab/translate-plugin/files/453195/Controller.zip)

**Comment by daftspunk** [comment]
Thanks, will take a look soon

**Comment by Obazure** [comment]
Hi there @blacked7, many thanks, your advice works.
