### ISSUE TITLE
URL's Languages

### ISSUE THREAD

**Issue by rafaelsfrutuoso** [rainlab/translate-plugin#166]
Awesome plugin! Thanks! I would like to know if it work for slug too. I would want to change the URL's languages to make a better SEO.

**Comment by CptMeatball** [comment]
`slug` translation is handled by the plugin that uses it. For example for the [Rainlab/Blog: Post Controller](https://github.com/rainlab/blog-plugin/blob/master/components/Post.php#L63) it uses the `transWhere` method instead of the `where` method.

Therefore it's up to the plugin author to handle multi language.

**Comment by daftspunk** [comment]
As above. Feel free to submit a PR to improve [the docs on this topic](https://github.com/rainlab/translate-plugin#url-translation).
