### ISSUE TITLE
 ML Repeater throws error @edit view (might be local cache)

### ISSUE THREAD

**Issue by CptMeatball** [rainlab/translate-plugin#182]
## Update: Looks to be a local cache error concerning the `$jsonable` array inside the model. If I encounter this problem again I'll update this thread.

Translate Version: 1.2.5
CMS Build: 377

When developing a custom plugin which uses the multi language implementation of the Repeater form-widget,  I ran into the following error when *updating* a record through the controller:

![screen shot 2016-11-01 at 10 52 53](https://cloud.githubusercontent.com/assets/1681727/19885919/852bdc00-a021-11e6-9994-9a45d76743fc.png)

Model:
![screen shot 2016-11-01 at 10 54 50](https://cloud.githubusercontent.com/assets/1681727/19885943/ad7ae0f2-a021-11e6-8778-c7e9f5d3213c.png)

fields.yaml:
![screen shot 2016-11-01 at 10 56 29](https://cloud.githubusercontent.com/assets/1681727/19885983/e16ece50-a021-11e6-8143-2c0f8b38ab16.png)

Database record plugin-model for `details` repeater field:
```
{"1":{"detail":"Detail Language 1"},"2":{"detail":"Detail Language 1 #2"}}

```

Database record rainlab_translate_attributes for corresponding plugin model:
```
{"title":"","slug":"","details":{"1":{"detail":"Detail Language 2"},"2":{"detail":"Detail Language 2 #2"}},"eyecatchers":null,"description":"","layout":"","location":""}

```

**Notes:**
- When removing the two repeater fields from `$translatable` the interface works as intended. But without ML functionality.
- The data is included in the component-model-view. So it is successfully saved.

**Comment by daftspunk** [comment]
This error is caused by an array value being passed to the translator without being declared as jsonable. There was a recent change made to force all `repeater` based fields in to this behavior.

I am confident this will fix it: https://github.com/rainlab/translate-plugin/commit/735a1b1ce0a1851094ea5f2c95fa4fe9b79cc4ce#diff-b38721aefb76699ef28a2f1abf7b5207R195

Otherwise please comment saying so and we will re-open this issue.
