### ISSUE TITLE
Generate a map of translated URLs for base redirects

### ISSUE THREAD

**Issue by mariavilaro** [rainlab/translate-plugin#189]
I noticed that if I change the locale and then I follow a link to a non-localized url to a page that has a translated url, I got a 404. Example:

I have the page About Us with url = "/about" and localeUrl[es] = "/acerca"

I change the language to es http://www.domain.com/es/

Now I follow a link to a page like http://www.domain.com/about and it redirects to http://www.domain.com/es/about so I got a 404. I think that I should be redirected to http://www.domain.com/es/acerca

(This is specially important because on Backend, the "Preview" link in all the CMS and Static Pages doesn't include the locale in them, so it doesn't work if the administrator last used locale is not the site's default)

**Comment by daftspunk** [comment]
This is likely because when you open `/es/acerca` the `es` locale is stored in the browser's session (it thinks this is your language now). So when you try to open `/about` it gives 404 because that is not the URL for `es` locale.

I can see how this might appear confusing. If the layout or page displayed a `localePicker` component -- or any element that shows the active locale -- the behavior would be more obvious, since the user would see the `es` locale is selected.

Not sure what the solution is to be honest...

**Comment by daftspunk** [comment]
On closer inspection, it is possible to fix this by [updating this line](https://github.com/rainlab/translate-plugin/blob/947794fb4644be7f88aa90c69ba16aca6af5fe2f/classes/Translator.php#L134) to:

```
$this->setLocale($locale, false);
```

Where the 2nd argument tells it to "not remember" the locale whenever it is provided by the URL.  We could implement a setting that controls this behavior, but it will produce inconsistent results. If the user sets the locale somehow, somewhere else in the app, the `/about` will no longer work for them and they will wonder why.

The setting would also need to force the locale to the default when it is omitted from the URL, regardless of the user's locale stored in the session. Just thinking out loud here.

**Comment by mariavilaro** [comment]
I was thinking in a workflow like this:

- user opens domain.com/about
- is there a locale in the url? > no
- is there a locale in the session > yes, es
- the page /about has a translation in the es language? > yes, /acerca
>>> redirect to /es/acerca

**Comment by daftspunk** [comment]
Makes sense. This is not easy today since a Page object only has a single URL when looking it up, so we would need to build a map of translated URLs to handle the routing.

**Comment by ctf0** [comment]
i think a solution could be, having an extra option where if the default local is == the current local, then we can omit the local from the url, otherwise include it.

this way u dont need to map the localized urls, the issue above wont occur.

this is the same as https://github.com/mcamara/laravel-localization `hideDefaultLocaleInURL`

**Comment by LukeTowers** [comment]
@mariavilaro is this something that you still need in the plugin?

**Comment by mariavilaro** [comment]
Yes, it's not really urgent but it would be nice that on Backend, the "Preview" link in the CMS and Static Pages always works. That 404 is confusing.

**Comment by LukeTowers** [comment]
If you made a PR for this I'd be happy to review it. You've done lots of great work with this plugin so far!

**Comment by mjauvin** [comment]
@mariavilaro am I right in saying this has been fixed by the "prefixDefaultLocale" setting in the plugin's config file (when setting prefixDefaultLocale=>false) ?

**Comment by mjauvin** [comment]
Closing this now @mariavilaro, if you think this has not been resolved please re-open.
