### ISSUE TITLE
Repeater individual field support.

### ISSUE THREAD

**Issue by raskrial** [rainlab/translate-plugin#190]
As mentionned in other threads, the repeater in Builder plugin seem to not save correctly translated individual field. When saving, the last data entered is considered and all other languages data entered are dropped. is there any way to make it work correctly or is there a work arround for this ?

**Comment by snipiba** [comment]
Same issue here...

**Comment by daftspunk** [comment]
This issue lacks enough detail or the replication instructions cannot be actioned easily. As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

Here is an example of a **bug summary**:

> The CMS page URL is not being set automatically from the title value.

Here is an example of some **reproduce steps**:

> 1. In the back-end, open the CMS > Pages section
> 1. Click the "Add" button
> 1. Enter [Hello] for the Title field
> 1. Click the Save button 

Here is an example of **expected behavior**:

> - The Title should be set to [Hello]
> - The URL should be set to [/hello]

Here is an example of **actual behavior**:

> - The Title is set to [Hello] correctly
> - The URL is left empty

**Comment by raskrial** [comment]
i have updated to the latest version of translate plugin. So here the summary of my current Bug

**Summary :** Repeater individual fields in Builders plugin not translating correctly.
**Reproduce steps:**

1. in a created plugin in Builder, i have a repeater with some fields, including a rich editor
2. in Model, i extended translate like the documentation and created an array with all fields that need translation
3. when entering data in fields contained in a repeater, i can fill in all languages but when i save, only the last language active in the fields is being saved and rich editor dont retain any data at all.
4. i have tried to translate the repeater as a whole. normal fields seem retaining all data but rich editor retain only default language data and drop all others.

**Comment by LukeTowers** [comment]
Duplicated in #218
