### ISSUE TITLE
The partial '_field_mltext.htm' is not found.

### ISSUE THREAD

**Issue by chrisvidal** [rainlab/translate-plugin#238]
October build 396

When opening a cms page, it throws this exception

Throws Exception
'October\Rain\Exception\SystemException' with message 'The partial '_field_mltext.htm' is not found.' in [redacted]/modules/system/traits/ViewMaker.php:65

**Comment by daftspunk** [comment]
Interesting, I haven't noticed this on my installation. Try enabling edge updates to see if it resolves the issue.

**Comment by virtualLast** [comment]
I have the same error, what would enabling edge updates do?

**Comment by virtualLast** [comment]
had to manually create the files to make the error go away

**Comment by LukeTowers** [comment]
You would have had to enable that setting and then update your October

**Comment by khoatran** [comment]
Guys, this issue happens because there is some differences in the way that OctoberCMS load form widgets in different version. 

I have exactly the same issue. Finally, I trace down to the code of Rainlab Translate plugin. At there, if you look at the function registerFormWidgets, you will see the code as below:

```
 public function registerFormWidgets() {
return [
            'RainLab\Translate\FormWidgets\MLText' => 'mltext',
            'RainLab\Translate\FormWidgets\MLTextarea' => 'mltextarea',
            'RainLab\Translate\FormWidgets\MLRichEditor' => 'mlricheditor',
            'RainLab\Translate\FormWidgets\MLMarkdownEditor' => 'mlmarkdowneditor',
            'RainLab\Translate\FormWidgets\MLRepeater' => 'mlrepeater',
        ];
}
```
If you are running an old version of October as my case (I haven't tried with the latest build 420), you will see this error. The way to fix it is: you will need to change this function into

```
 public function registerFormWidgets()
    {
        return [
            'RainLab\Translate\FormWidgets\MLText' => ['code' => 'mltext'],
            'RainLab\Translate\FormWidgets\MLTextarea' => ['code' => 'mltextarea'],
            'RainLab\Translate\FormWidgets\MLRichEditor' => ['code' => 'mlricheditor'],
            'RainLab\Translate\FormWidgets\MLMarkdownEditor' => ['code' => 'mlmarkdowneditor'],
            'RainLab\Translate\FormWidgets\MLRepeater' => ['code' => 'mlrepeater'],
        ];
    }
```
I hope this can help.

Cheers,

**Comment by LukeTowers** [comment]
The code to support converting the new method to the old method has been in October since Build 378. See https://github.com/octobercms/october/commit/bc165078deada0b852e736e0b2cab4219113b411#diff-34e42a18a94b81013305d1b5c5f69d42R101

I highly recommend that you update your October instance.

**Comment by khoatran** [comment]
Yes, Luke. I will. However, you know, process to upgrade things in big companies takes time and we need to verify very careful for every changes :). Btw, thanks for your help to point out the code changes

**Comment by khoatran** [comment]
I've just thought about another issue related to this. Somehow, the plugin must provide the backward compatibility with different versions of OctoberCMS.

In this case of the translate plugin, if the plugin author knows the version of the OctoberCMS core, he can rewrite the code to support different versions easier, just by adding checking version logic to call the proper method.

So, the question here is: how OctoberCMS release the version and can we get the version by the code ? I am sorry if this question is so obvious (in case everyone knows the way to get OctoberCMS version from the code but I don't know) :). I haven't checked into the OctoberCMS code deeply to get this answer yet.

**Comment by LukeTowers** [comment]
@khoatran we don't support that approach in October. By default, you are not able to update plugins without also updating core. Thus, plugins should not have to support older versions of core. But, if you were restrained into something like that then you could probably look at using the system parameter model to get the core build information.

As a side note, this could be fixed for all versions of October simply by changing it to the array approach instead of the string approach.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

**Comment by yapsr** [comment]
Experiencing the same issue using October CMS version 2.2.35 and Rainlab Translate plugin v1.12.0

**Comment by daftspunk** [comment]
This looks like a different issue from a long time ago, @yapsr.
