### ISSUE TITLE
Issue with plugin integration 

### ISSUE THREAD

**Issue by ajinkyakambe** [rainlab/translate-plugin#293]
http://webmshare.com/play/jBGyW

I want to integrate plugin as shown in above video. 
It's not working?
Can you please solve this issue?

**Comment by LukeTowers** [comment]
The amount of time spent asking for help is directly related to the amount of time spent putting in effort to answer it. If you want help and / or guidance, then invest as much time as possible in making questions that are detailed and easy to understand. Otherwise, nobody is going to invest their time helping with a question that wasn't even worth the askers time to ask correctly.

Closing as it has been over a month since any activity on this occurred.
