### ISSUE TITLE
After update

### ISSUE THREAD

**Issue by giorgionetg** [rainlab/translate-plugin#342]
After update and get latest version (1.3.3). The plugin seems installed, but the widget does not work at all. It's like if it was not installed.

**Comment by LukeTowers** [comment]
Not enough information. 
The amount of time spent asking for help is directly related to the amount of time spent putting in effort to answer it. If you want help and / or guidance, then invest as much time as possible in making questions that are detailed and easy to understand. Otherwise, nobody is going to invest their time helping with a question that wasn't even worth the askers time to ask correctly.

**Comment by giorgionetg** [comment]
SOLVED!!!
I had two folders of translate plugin "rainlab/translate" and "rainlab/translate_old", before update works regular, but after nope. My mistake.
I apologize for time wasting.
Thanks for fast reply.
