### ISSUE TITLE
Domain instead of subfolder for language ?

### ISSUE THREAD

**Issue by daslicht** [rainlab/translate-plugin#356]
Hi,
is it possible to use different domains for each language, please ?

```
German -> ansolas.de
English -> ansolas.com 
```

?

**Comment by munxar** [comment]
You could try to use a middleware and check for your domains like this:

```php

use RainLab\Translate\Classes\Translator;
use System\Classes\PluginBase;

class Plugin extends PluginBase
{
    public function boot()
    {
        \Cms\Classes\CmsController::extend(function($controller) {
            $controller->middleware(function($request, $next) {
                $translator = Translator::instance();
                $serverName = $request->server->get('SERVER_NAME');

                switch($serverName) {
                    case 'ansolas.de':
                        $translator->setLocale('de');
                        break;
                    case 'ansolas.com':
                        $translator->setLocale('en');
                        break;
                }

                return $next($request);
            });
        });
    }
}

```

**Comment by daslicht** [comment]
awesome ! Thank you very much !

**Comment by PubliAlex** [comment]
Hello,

This solution works well to provide the good language depending on the domain, but how to create link that do that switch ?

If you use the onSwitchLocale() method, it doesn't work

If you hardcode www.mywebsite.com, www.mywebsite.de, www.mywebsite.fr in the href of the links, it works, but you return to homepage each time instead of having a translated version of the page you actually see.

What is your solution to this problem ?

thank you
