### ISSUE TITLE
Home page URL translated automatically for non-default languages

### ISSUE THREAD

**Issue by kirinokisu** [rainlab/translate-plugin#361]
I've never encountered this kind of bug in this plugin before, but for some unexplainable reason, it **automatically** translates the home/index page url for non-default languages. 

The default language is set as Finnish and the url is the root: website.fi/ 
Which should be the same for all the other languages (it certainly works in all other projects). But instead, for Russian and English languages, the plugin automatically fills the url-field and turns it into website.fi/isle-vikings which I guess is taken from the title (Isle of Vikings). Removing it doesn't work, it just fills automatically again, every time. Forcing the en/fi/ru schema doesn't help either; the plugin still changes the home page address for non-default languages. So if someone picks non-default language first time they visit, next time they go to the website, they get Error 404 because the home page for that language is not website.fi/ 

Any idea what might be causing this/how to fix it?

**Comment by vannut** [comment]
This happens because by default the choosen locale is stored in a session. So if you change the locale; and then revist the website with the previous (old locale) url it returns a 404, because it is searching in the new locale for the url in the old locale. 
Does that makes any sense?

Solution: use `forceUrl` in the localepicker this will always put a locale prefix to the URL so it doesn't look at the session anymore. 
If you don't want to prefix the default locale change [this setting to false](https://github.com/rainlab/translate-plugin/blob/master/config/config.php#L14)

**Comment by anastasiauz** [comment]
It turns out that without forceUrl checked in the localepicker solution with translatable slugs is not working normally, non-default language urls are not accessible and give 404 unless you visit main domain page ('/') and switch to that language. Your non-default languages' pages won't be shareable in social networks or crawlable by search robots. It should be marked somewhere in documentation or -better - fixed somehow. It doesn't seem right at all... @vannut many thanks for pointing to that, I was looking for solution for quite a long time, and it turned out to be so easy.

**Comment by geez0x1** [comment]
I'm seeing the exact behaviour anastasiauz mentions. I'm testing a website in multiple tabs - when switching languages on one and refreshing any of the others, the reload gives a 404. Will now test what `forceUrl` does for me. This is really poor behaviour.
