### ISSUE TITLE
translate php date object not working

### ISSUE THREAD

**Issue by Antar74** [rainlab/translate-plugin#379]
Hi! I'm using your awesome plugin, that works just fine. I have several places where I need to show the  publishing date (of a blog post using Rainlab.blog plugin). Out of the box the date is translated, but I had to extend the blog plugin to have an extra date filed (for post that need to show a future date that is different from the publishing date, as in a future event post). So I managed to extend the Rainlab.blog plugin. But the new date object that I created is not being translated :(

Am I missing something, should I register this new date object somewhere in your plugin to get it translated?

I'm attaching the files I used to extend the blog plugin. Please help!

[kuri.zip](https://github.com/rainlab/translate-plugin/files/2082474/kuri.zip)

**Comment by LukeTowers** [comment]
Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: http://octobercms.com/forum
StackOverflow: http://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/

**Comment by LukeTowers** [comment]
@Antar74 as an aside, I don't see a date field being added in that plugin?

**Comment by mjauvin** [comment]
@antar74 your field would need to be added to the $translatable[] array in the model.
