### ISSUE TITLE
Some UI Improvements directly from clients

### ISSUE THREAD

**Issue by ghost** [rainlab/translate-plugin#384]
Hello,

I made some projects with October CMS recently, some of them was multilanguage.

When I present the backoffice to the customers, there are really impressed by the ease of use of it to manage blog posts, portfolio etc.... 

But each time, I got 2 features requests related to the translate plugin, that's why I'm posting here. Not critical issue but some UI suggestions to make it even more better : 

- Add an option to copy content from the original language when you translate a field.
By default, when you change language for a field, it is emptied. Most translators prefers to have the original language copied in order to keep a view on it while translating.

- Add an option to switch all fields on the form to the other language
Minimal issue, but when you deal with a form that contain a lot of fields, It's quite annoying to have to switch language for each of them. It would be great to have a general switching field (somewhere on the right in the breadcrumb would be a good position) it order to switch them all in one click.

Besite that, all customers are really happy with their backoffice. Continue the great work !

Best regards,

Alex

**Comment by Alex360hd** [comment]
Just discovered that you can already switch all fields in one click by pressing ctrl (or CMD for mac) when switching locale in the backoffice !

There is still the first point that would be a great improvement (or it's already possible and I missed the other shortcut ? :) )

**Comment by vannut** [comment]
Good remarks. 
You already found the answer for your second question 👍 

Regarding your first answer; this could be a good improvement! Although we need to think of some UI/UX problems like: how do we distinguish the 'copied' content.
What we don't want to happen is to get the copied content being saved as the new language content.

So we might have to add some UI control to 'copy from' or something,  instead of pre-populating the field with an other language's content when null.

(Does that makes sense?)

**Comment by Alex360hd** [comment]
Here is the logic I would apply : 
When I switch language for a field : 
- Check what is the default language of the website
- Check if the field have content in the original language
- Check if the field have content in the translated language
- If not, copy the content of the original language to that translated field 
- If yes, don't touch anything, you don't want to see your translated text replaced by the original one

Nothing would be saved at the moment. User still have to click to "save" button to save anything.

Maybe this behavior could be a option that you can enable / disable per model (per field would be cumbersome and rarely useful) for people that prefers to start from scratch when they translate a content.

**Comment by AugmentBLU** [comment]
I would agree that copying the original content to another language would be super helpful and drastically cut down time for content editors. Rather than a magical check on the original content, perhaps a drop down with copying options would be better so you have a little control over what is being copied over. If you have 2 languages, the dropdown could have a single option "copy from original", if there's several translations already, "copy from X, Y, Z" could be helpful. 

Not sure how this would all work, especially if you have a complex use case with repeaters and grouped elements.

**Comment by mjauvin** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
