### ISSUE TITLE
Once after added translation code, getting an error the frontend. 

### ISSUE THREAD

**Issue by tijosfx** [rainlab/translate-plugin#393]
Once after added  {{ '     '|_ }} this in all text, getting an error in the frontend. 

please check the url
http://b66.projectshowcase.net/

Once after remove the "$" then next error will show: check this screen http://prntscr.com/kfewi0
I have removed that also but the next issue is http://prntscr.com/kfexv8

Can you help me to fix the issue?

Thanks
Tijo

**Comment by LukeTowers** [comment]
While it is technically correct to provide translation keys in this manner, for the strings that you are dealing with I'd recommend just writing actual keys and then translating those though the backend settings menu (i.e. `{{ 'homepage.problem.description' | _ }}` and `{{ 'team.member.' ~ personName ~ '.name' | _ }}`). Look at https://github.com/rainlab/bonjour-theme/blob/master/theme.yaml#L10 for a demonstration of how you could provide those translations in the code of your theme instead of through the backend translation database.

As an aside, Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

StackOverflow: http://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/
