### ISSUE TITLE
How to translate fields jsonables

### ISSUE THREAD

**Issue by adc91** [rainlab/translate-plugin#411]
Good,

I've been looking for a lot and I really have not found any solution that works for me for the problem I'm having.

I have a field 'body' which is jsonable. I have it in 'es' => Spanish and 'en' => English. From the backend I can select and load the text in both languages.

The problem I have is that I am not able to translate it from the frontend. I have tried with fields not jsonables and it works perfectly.

I have tried in several ways but it always shows in the default language that it is Spanish (es)

**Model.php**
<img width="957" alt="captura de pantalla 2018-10-02 a la s 22 40 08" src="https://user-images.githubusercontent.com/11680570/46387460-cb1dfe00-c694-11e8-9853-19ae218db61d.png">

Fields.yaml
<img width="500" alt="captura de pantalla 2018-10-02 a la s 22 40 18" src="https://user-images.githubusercontent.com/11680570/46387476-d5d89300-c694-11e8-9299-6f800163d984.png">

**Component**
<img width="639" alt="captura de pantalla 2018-10-02 a la s 22 42 00" src="https://user-images.githubusercontent.com/11680570/46387513-fb659c80-c694-11e8-9b57-4c8bc11e8098.png">

From already thank you very much.

**Comment by osmanzeki** [comment]
I believe this is due to an issue with how jsonable fields are sometimes not `json_decode`'ed properly.

I'm trying to work on a fix for this. See my fork (please do read the README as it explains my discovery and tentative for a fix) here:

https://github.com/osmanzeki/octobercms-jsonable-fix/blob/master/README.md

Help testing the proof of concept there would be appreciated. It does not work 100% yet and is very hackish so a real Pull Request could be worked on once we know how to fix this for real.

**Comment by LukeTowers** [comment]
Duplicate of #191
