### ISSUE TITLE
Error removal

### ISSUE THREAD

**Issue by Wambua47** [rainlab/translate-plugin#498]
How can this error be removed please?
Caused by:PDException
SQLSTATE(23000):Integrity constraint violation:1062Duplicate entry"33133828" for key 'id-no-UNIQUE'

**Comment by bennothommo** [comment]
@Wambua47 Please provide a backtrace and more info on where this exception occurs.

**Comment by Wambua47** [comment]
SQLSTATE(23000):integrity constraint violatio:1062 Duplicate entry"33133828" for key 'id-no-UNIQUE

**Comment by Wambua47** [comment]
How can that error be removed??

**Comment by LukeTowers** [comment]
@Wambua47 we need to see a full stack trace and detailed replication instructions in order to help you. 

The amount of time spent asking for help is directly related to the amount of time spent putting in effort to answer it. If you want help and / or guidance, then invest as much time as possible in making questions that are detailed and easy to understand. Otherwise, nobody is going to invest their time helping with a question that wasn't even worth the askers time to ask correctly.

**Comment by w20k** [comment]
@Wambua47 remove the duplicated entry from DB or change id, manually.

**Comment by w20k** [comment]
@Wambua47 hacking your DB manually :) Not through the website, don't think it's possible. You have an overlap somehow - somewhere. If you want a fix for that, better to provide steps to reproduce or more info.

**Comment by Wambua47** [comment]
How can i do this and i dont know much about computer software???

**Comment by w20k** [comment]
Better to find a Dev to do that, if you're not a software developer. Much easier!

**Comment by Wambua47** [comment]
Can you assist me if ur one???

**Comment by mjauvin** [comment]
Please use the forum for help.
