### ISSUE TITLE
Field layout issues on mobile

### ISSUE THREAD

**Issue by mjauvin** [rainlab/translate-plugin#575]
The new functionality introduced by PR #565 introduces layout positioning issues on mobile (specifically with the "hide translated" checkbox).

See screenshots below:

Before:
![Screenshot_20200420-090512](https://user-images.githubusercontent.com/2013630/79754860-2a2e7c80-82e6-11ea-968f-be05a2b8830c.jpg)

After:
![Screenshot_20200420-090712](https://user-images.githubusercontent.com/2013630/79755010-6235bf80-82e6-11ea-8903-9b338a3ef124.jpg)

@multiwebinc can you look into this?

**Comment by multiwebinc** [comment]
The problem is that it is getting cut off due to the following CSS rules:

```css
.control-table table.headers th {
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}
```

What should the smallest supported screen width be? I think the solution depends on that. For me on Chrome, the checkbox is currently visible down to 433px screen width. If I instead make the width of the "scan errors" column width 20vh, the checkbox is visible down to 373px screen width, which would be more acceptable.

Another solution would be to move checkbox to after the text, so the thing that gets cut off first is the text and the checkbox remains visible always.

However with that said, other parts of the backend also do not behave very well with low resolutions, so I don't think it is *that* big of a problem:

For example:

The media library at 760px:
![image](https://user-images.githubusercontent.com/901732/79940421-e8edb800-841e-11ea-8db7-b98138d368bc.png)

Then again at 484px:
![image](https://user-images.githubusercontent.com/901732/79940456-028eff80-841f-11ea-8662-dbe7d05afae9.png)

On the builder plugin, you can't realistically choose a plugin below about 400px screen width since you need to click on the part with the darkened overlay, which completely disappears at 360px. Here it is at 400px. Any smaller than this and it's really hard to tell you need to be clicking there:
![image](https://user-images.githubusercontent.com/901732/79941145-d2e0f700-8420-11ea-89a1-3b2f360805ff.png)

**Comment by mjauvin** [comment]
@multiwebinc from the test I ran, width of 105px with the `info` icon on the left yields the best results.

**Comment by multiwebinc** [comment]
105px for me always truncates the text (even on large resolutions) and even then, I can only scale it down to 392px before the checkbox starts being truncated. It needs to be at least 115px for me to see both the text and the info icon. This could be due to differences in fonts used. However it's probably not a good idea to cut it so close either, especially since when that string is translated to other languages, it could be significantly longer. That's why I gave a little bit of extra growing room and set it initially to 150px. However I'm leaning more towards viewport units or percentage units. Setting it to 20vw, the checkbox is visible at 372px screen width, and if I set it to 15vw, it's visible at 350px screen width.
