### ISSUE TITLE
Exception when calling an URL in an other language

### ISSUE THREAD

**Issue by oliverpool** [rainlab/translate-plugin#61]
Hi,

I'm trying to set up the translate plugin, but I can't get it to work.
My site is initially in french (fr) and I want to have en english translation (en).

I think I set up everything fine, but when I call the URL localhost/en/, I have the following exception:
```
Call to undefined method Cms\Classes\Controller::getAfterFilters()

/.../october/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php line 202
```

I did a `dump` of `$instance` and it is of the class `Cms\Classes\Controller` (with does not have any `getAfterFilters()`)
The normal request (without language prefix), uses a `Cms\Classes\CmsController`.

PS: I'm using the latest build (247) of octoberCMS and version 1.0.9 of the translate plugin (I also tried to disable all the other plugins, but it didn't solve my problem)

**Comment by jh2odo** [comment]
Hi,

The solution is modify the routes.php file of plugin.

.../plugins/rainlab/translate/routes.php

Origin: `Route::any('{slug}', 'Cms\Classes\Controller@run')->where('slug', '(.*)?');`

Solution:  `Route::any('{slug}', 'Cms\Classes\CmsController@run')->where('slug', '(.*)?');` 

With that, it will run well.

I think that the problem is the change a the new version laravel 5 and this plugin don't update to RC version OctoberCMS.

Reference: https://github.com/octobercms/october/commit/1a037bad04c604a8df94ed3403342e0c0824a7cd

**Comment by oliverpool** [comment]
It works perfectly: thanks!

*I let the issue open until the merge of your PR*
