### ISSUE TITLE
A way to change font-family based on language

### ISSUE THREAD

**Issue by Dione-stack** [rainlab/translate-plugin#626]
Hello, i am looking for a way to change font-family based on language using this plugin, example: English = Arial, Greek = Roboto
How can i achieve that?

**Comment by mjauvin** [comment]
$locale = App::getLocale();

Then choose font with $locale value.

**Comment by Dione-stack** [comment]
Hello again, i am very sorry to bother you again, the reason why i wanted to use 2 fonts is because the text in Arabic language is not readable, unfortunately changing font did not fix it, i need to be able to style the Arabic text alone without messing with the English text

If the only way i can fix this is through PHP, I request that you give me some hints on how i can get it to work because i'm still learning, or if it won't take much of your time maybe you can give me a working code, and if i am asking for too much then i understand, thank you

![Untitled-1](https://user-images.githubusercontent.com/67985418/100492313-1fb14c80-312b-11eb-8810-39610991246b.jpg)

**Comment by mjauvin** [comment]
I'm not versed in Arabic language, other than RTL, is there something else that need to be changed?

You could use the locale variable to add a css class to the text that needs to be adapted and use the CSS "direction" property to do this.

I suggest using the forum, stackoverflow or the Discord channel if you need help with this instead of a git issue.
