### ISSUE TITLE
Let admins decide to store the language (locale) in the session

### ISSUE THREAD

**Issue by oliverpool** [rainlab/translate-plugin#63]
To address #42 and #57, I think it could be a good idea to allow the admin to decide whether or not the current locale should be stored in the session.

It could be file-based, with a key like `sessionStored`.

Either it's only code editable (config.php file), or it belong to some configuration page.

I would prefer a configuration page, which would also gather other parameters:
- Store the lang in the cookies
- Prevent content duplication: 
  - Always redirect to URL with lang suffix
  - Always redirect to URL with lang subdomain prefix
  - ...
  - _Nothing_
- Access the default lang via the canonical URL (without suffix/prefix)

**Comment by 7talents** [comment]
+1 for this!
In my projects "no locale in the URL" always means the default language, so switching to that URL should activate the default language...

**Comment by Flo-Schield-Bobby** [comment]
+1!

**Comment by Kunilt** [comment]
+1

**Comment by LukeTowers** [comment]
Please only use GitHub Issues for feature requests if you are using it as a pre-Pull Request collaboration tool. If you aren't planning on implementing it yourself, then it would be better suited being asked for on one of these channels:

Forum: http://octobercms.com/forum
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/

The support demand for October is increasing, while the available time the founders have to give remains the same. Feature requests are by default the lowest priority for us, as we don't have time to implement everyone's suggestions by ourselves. However there are ways you can help:

- Submit a pull request that introduces this feature and we'll review it. Please note that the amount of effort making the PR (code quality, rationale for inclusion in the project, explanation of changes) is directly proportional to the likelihood that we will review and merge it.
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

Closing as it has been over a month since any activity on this occurred.
