### ISSUE TITLE
FatalThrowableError after installing Translate Plugin

### ISSUE THREAD

**Issue by massimomegistus** [rainlab/translate-plugin#638]
OctoberCMS Build: 2.0 (Clean install)
RainLab Translate Plugin Version: 1.7.4
PHP Version: 7.4
Description:
After installing Translate Plugin
Class 'October\Rain\Database\Behaviors\Purgeable' not found
~/vendor/october/rain/src/Extension/ExtendableTrait.php line 215

Steps To Reproduce:
APP_DEBUG=true
php artisan plugin:install rainlab.translate
Go to backend/

**Comment by daftspunk** [comment]
Hey @massimomegistus

Please run **composer update** to update to `october/rain:2.0.1` and `rainlab/translate-plugin:1.8.0`

Then it should be fixed. Thanks for helping test October CMS

BTW, since this plugin resides under the officially managed group of plugins (RainLab org). You may continue to submit [2.0] issues to [the main repo](https://github.com/octobercms/october/issues), as it will get faster attention there
