### ISSUE TITLE
Searching the Translate Messages list fails after entering a translation

### ISSUE THREAD

**Issue by chocolata** [rainlab/translate-plugin#673]
Hi, another mention of a small, minor bug. If you search the Translate Messages list, and then enter of change some translation, you will notice that the search function fails to work after this. You have to refresh the page to be able to search again. Could you guys look into this? This would make bulk translating a lot easier.

**Comment by daftspunk** [comment]
This has been fixed in October CMS v3.1. We have tested it using the latest version and appears to be working normally.

- Link to the [upgrade guide](https://github.com/rainlab/translate-plugin/blob/master/UPGRADE.md)
- Link to [multisite documentation](https://docs.octobercms.com/3.x/cms/resources/multisite.html)

If this is still an issue, feel free to get in touch with the support desk for assistance: https://octobercms.com/contact
