### ISSUE TITLE
Mail template translation in OctoberCMS 2.2.34: is it supported?

### ISSUE THREAD

**Issue by massimomegistus** [rainlab/translate-plugin#698]
OctoberCMS 2.2.34
Rainlab.Translate 1.12.0
Hello,
according to the plugin documentation, mail template seems to be translatable (just like theme content), but in the backend I can't find a way to switch Mail template to secondary languages.
I'm a little confused....

Thank you for the support!

**Comment by daftspunk** [comment]
Hi @massimomegistus 

Thanks for your question. The mailer template translation works the same as the cms content. For example:

* **welcome.htm** will contain the mail template in the default language.
* **welcome-fr.htm** will contain the mail template in French.

This is the approach used in the filesystem for seeding the mail content and you should also be able to specify them in the mail codes when creating templates in the admin panel. For example `rainlab.user::mail.invite` and `rainlab.user::mail.invite-fr`.

In OCMS v3.1 there is a global site picker that is introduced, we may look at improving this feature to support switching languages instead of supplying them in the template code.

I hope this helps.

**Comment by chocolata** [comment]
Hi, please note the documentation shows welcome.fr.htm instead of welcome-fr.htm. 

Regards.

**Comment by daftspunk** [comment]
Thanks, docs have been updated
