### ISSUE TITLE
How to get the translated file from the Model

### ISSUE THREAD

**Issue by chaturadilan** [rainlab/translate-plugin#725]
Now I tested in Translate v2.2.7 and OctoberCMS v3.4.11, Now I'm not getting the translated attachment field at all

_Originally posted by @chaturadilan in https://github.com/rainlab/translate-plugin/issues/722#issuecomment-1659938353_

**Comment by chaturadilan** [comment]
Hi

I have created a translatable file like following,

```
public $implement = [ \RainLab\Translate\Behaviors\TranslatableModel::class];

 public $translatable = ['image'];
 public $with = ['image'];

public $attachOne = [
        'image' =>  \System\Models\File::class,
];
```

I was able to add translated files using the Admin Backend, and I both see it in system_files.

But when I try to access the model like below, it always returns the file that is set for 'en' but nor 'fr'

`$model->lang('fr')
`

for translated model it does not return the attachment

**Comment by daftspunk** [comment]
Hey @chaturadilan 

#722 has a working example of this. You can test this by installing the test plugin here:

https://github.com/octobercms/test-plugin

Navigate to "Pages" and upload a file to the "Photo" field.

I hope this helps.

**Comment by mabehiry** [comment]
the problem is in retrieving records

https://github.com/rainlab/location-plugin/blob/master/models/Country.php#L71

when we call directly using ->lists('name', 'id'); translation relation is not loaded.

but if you change this line from

return self::$nameList = self::isEnabled()
     ->orderBy('is_pinned', 'desc')->lists('name', 'id');
to

return self::$nameList = self::isEnabled()
     ->orderBy('is_pinned', 'desc')->get()->lists('name', 'id');
                                ----- ^ <- this one
It load translation relations and works fine.

I suggest editing these lines in the plugin so we don't worry about update
